Created an app and linked database
SEI-39/developerverse pull request #24
Opened 2020-10-06 18:38 UTC by AbsurdlyEloquent

## Related Issues (include the `#`)
issue #23 

## Description of Changes Made
- ran `manage.py startapp` to make a django app
- added the app to settings.py
- configured postgres in settings.py
- refactored settings.sql to have more reflective database names

## Questions or Comments (optional)
I think the project should be renamed to something like 'developerverse_project' to avoid confusions...

2020-10-06 20:27 UTC, midastouchprd requested changes
Just one small change

2020-10-06 20:27 UTC, midastouchprd commented on back-end/developer_verse/settings.py
> +        'PORT': '5432'
lets go ahead and make these env variables now

2020-10-07 13:40 UTC, Underwaterr approved these changes
Looks great. Please inform the other devs about environment variables and document how to set it up in the wiki!

2020-10-07 13:41 UTC, Underwaterr approved these changes

2020-10-07 13:42 UTC, merged