User routes
SEI-39/developerverse pull request #66
Opened 2020-10-12 21:45 UTC by AbsurdlyEloquent

## Related Issues (include the `#`)
#27 

## Description of Changes Made
Added class views for creating and authenticating a user that return a token

## Questions or Comments (optional)
I know this is way too much work for 3 commits, I got caught up

2020-10-13 13:17 UTC, Underwaterr requested changes

2020-10-13 13:17 UTC, Underwaterr commented on back-end/users/views.py
> +            return Response(None, status=status.HTTP_401_UNAUTHORIZED)
This feels like too much logic for a view in Django REST Framework. Wouldn't this be better handled with serializers?

2020-10-14 14:57 UTC, iandemed approved these changes

2020-10-14 14:58 UTC, iandemed approved these changes

2020-10-14 15:10 UTC, merged